name: Release lib-rift

on: 
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Define release tag'     
        required: true

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Obtain lib-rift (Ubuntu)
      id: download-artifact-linux
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ubuntu-compile-rift-lib.yml
        workflow_conclusion: success
        branch: master
        if_no_artifact_found: fail

    - name: Obtain lib-rift (Win64)
      id: download-artifact-win
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: windows2019x64-compile-rift-lib.yml
        workflow_conclusion: success
        branch: master
        if_no_artifact_found: fail

    - name: Obtain lib-rift (macOS)
      id: download-artifact-mac
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: macos-10.15-compile-rift.yml
        workflow_conclusion: success
        branch: master
        if_no_artifact_found: fail
    - name: Gather Artifacts
      run: |
        mkdir release
        cp rift-lib-macos/rift-lib.dylib release/rift-lib-macOS.dylib
        cp rift-lib-ubuntu-18.04/rift-lib.so release/rift-lib-ubuntu-18.04.so
        cp rift-lib-ubuntu-20.04/rift-lib.so release/rift-lib-ubuntu-20.04.so
        cp rift-lib-ubuntu-22.04/rift-lib.so release/rift-lib-ubuntu-22.04.so
        cp rift-lib-win64/rift-lib.dll release/rift-lib-win64.dll
        ls -R 
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release/*.*"
        tag: ${{ github.event.inputs.release_tag }}
        commit: master
